spring:
  datasource:
    url: jdbc:h2:mem:budgetmanagementsystem;INIT=RUNSCRIPT FROM 'classpath:/db/scripts/schema.sql'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect